language: generic
sudo: required
dist: trusty
compiler: gcc

branches:
  only:
  - master
  - "/^release.*$/"

cache:
  directories:
  - build/sstate-cache

before_cache:
  - cd build ; ../yocto/poky/scripts/sstate-cache-management.sh -y -L -d --cache-dir=./sstate-cache

env:
- PLATFORM=appliance
- PLATFORM=genericx86-64
- PLATFORM=as5712
- PLATFORM=as6712
- PLATFORM=as7712
#currently broken due compiler flags
#- PLATFORM=as7512
#- PLATFORM=mlnx-sn2xxx
# these are missing opennsl
#- PLATFORM=as5812t
#- PLATFORM=as5812x

addons:
  ssh_known_hosts: yocto.libreswitch.org

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq gawk wget git-core diffstat unzip texinfo build-essential
  chrpath screen curl device-tree-compiler
install: true

script:
- make configure $PLATFORM
- travis_wait 50 make

before_deploy:
- openssl aes-256-cbc -K $encrypted_2b923ab06c69_key -iv $encrypted_2b923ab06c69_iv
  -in tools/ci/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR/build/sstate-cache/ && rsync -avzL --progress ?? universal libreswitch-ci@yocto.libreswitch.org:/data/yocto-cache/sstate-cache/
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a392ac25d47cc2eaf127
  on_success: change
  on_failure: always
  on_start: never
